java-8-defaults: &java-8-defaults
  working_directory: ~/build-working-directory
  docker:
    - image: circleci/openjdk:8-jdk
      environment:
        JAVA_OPTS: -XX:+UseG1GC
        # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
        GRADLE_OPTS: -Xmx512m -Xms256m -Dkotlin.compiler.execution.strategy="in-process"

shared-steps:
  generate-cache-key: &generate-cache-key
    run:
      command: |
        mkdir -p build
        find settings.gradle.kts build.gradle.kts gradle buildSrc/src buildSrc/build.gradle.kts -type f -exec sha256sum '{}' \; | tee build/circle-ci-key.txt
      name: Generate cache key
  restore-home-cache: &restore-home-cache
    restore_cache:
      keys:
        - v2-home-cache-{{ checksum "build/circle-ci-key.txt" }}
        - v2-home-cache-
  save-home-cache: &save-home-cache
    save_cache:
      paths:
        - ~/.gradle
      key: v2-home-cache-{{ checksum "build/circle-ci-key.txt" }}
      when: always
  show-java-info: &show-java-info
    run:
      command: |
        java -XshowSettings:vm -XX:+PrintCommandLineFlags -version
        java -XshowSettings:vm -XX:+PrintCommandLineFlags -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -version
        javac -version
      name: Show Java Version
  junit-platform-test-results: &junit-platform-test-results
    store_test_results:
      path: ~/build-working-directory/build/test-results/

version: 2
jobs:
  check:
    <<: *java-8-defaults
    steps:
      - checkout
      - *generate-cache-key
      - *restore-home-cache
      - run:
          command: ./gradlew build -PgradleTestVersions=current --max-workers 2 --stacktrace  --scan
          name: Test With Current Gradle Wrapper Version
      - *junit-platform-test-results
      - *save-home-cache
      - persist_to_workspace:
          root: ~/build-working-directory
          paths:
            - .gradle/*
            - build/*
            - buildSrc/.gradle/*
            - buildSrc/build/*
            
  test-gradle-4.6:
    <<: *java-8-defaults
    steps:
      - checkout
      - *generate-cache-key
      - *restore-home-cache
      - attach_workspace:
          at: ~/build-working-directory
      - run:
          command: ./gradlew build -PgradleTestVersions=4.6 --max-workers 2 --stacktrace
          name: Test With Gradle 4.6
      - *junit-platform-test-results

  test-gradle-4.7:
    <<: *java-8-defaults
    steps:
      - checkout
      - *generate-cache-key
      - *restore-home-cache
      - attach_workspace:
          at: ~/build-working-directory
      - run:
          command: ./gradlew build -PgradleTestVersions=4.7 --max-workers 2 --stacktrace
          name: Test With Gradle 4.7
      - *junit-platform-test-results

  test-gradle-4.8:
    <<: *java-8-defaults
    steps:
    - checkout
    - *generate-cache-key
    - *restore-home-cache
    - attach_workspace:
        at: ~/build-working-directory
    - run:
        command: ./gradlew build -PgradleTestVersions=4.8 --max-workers 2 --stacktrace
        name: Test With Gradle 4.8
    - *junit-platform-test-results

workflows:
  version: 2
  build:
    jobs:
      - check
      - test-gradle-4.6:
          requires:
            - check
      - test-gradle-4.7:
          requires:
            - check
      - test-gradle-4.8:
          requires:
          - check
